apply plugin: 'maven-publish'
apply plugin: 'signing'

group = "io.github.yvescheung"                               // Maven Group ID for the artifact
version = libraryVersion
final String developerId = 'YvesCheung'
final String developerName = 'YvesCheung'
final String developerEmail = '975135274@qq.com'
final String licenseName = 'The Apache License, Version 2.0'
final String licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0'

/**
 * ossrhUsername
 * ossrhPassword
 * signing.keyId
 * signing.password
 * signing.secretKeyRingFile
 * Variables defined in local.properties
 */
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if (localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
}

afterEvaluate {
    publishing {
        if (properties['ossrhUsername'] != null) {
            repositories {
                maven {
                    name = 'ossrh-staging-api'
                    url = "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"

                    // The username and password we've fetched earlier
                    credentials {
                        username properties['ossrhUsername']
                        password properties['ossrhPassword']
                    }
                }
            }
        }

        publications {
            MyPublication(MavenPublication) {
                from components.release
                groupId group
                artifactId libraryName
                version libraryVersion
                pom {
                    name = libraryName
                    description = libraryDescription
                    url = siteUrl

                    developers {
                        developer {
                            id = developerId
                            name = developerName
                            email = developerEmail
                        }
                    }

                    scm {
                        connection = gitUrl
                        developerConnection = gitUrl
                        url = siteUrl
                    }

                    licenses {
                        license {
                            name = licenseName
                            url = licenseUrl
                        }
                    }
                }
            }
        }
    }

    if (properties['signing.keyId'] != null) {
        ext['signing.keyId'] = properties['signing.keyId']
        ext['signing.password'] = properties['signing.password']
        ext['signing.secretKeyRingFile'] = properties['signing.secretKeyRingFile']
        signing {
            sign publishing.publications
        }
    }
}

//https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#ensuring-deployment-visibility-in-the-central-publisher-portal
tasks.register('ensuringDeploymentVisibility') {
    doLast {
        def username = properties['ossrhUsername']
        def password = properties['ossrhPassword']
        def url = "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.yvescheung"
        // 发送 POST 请求，使发布文件能在 central sonatype 中显示
        def connection = new URL(url).openConnection() as HttpURLConnection
        connection.setRequestMethod("POST")
        connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded")
        connection.setRequestProperty('Authorization', 'Basic ' + "${username}:${password}".bytes.encodeBase64().toString())
        connection.doOutput = false

        def response = connection.inputStream.text
        println "POST 响应: ${response}"
    }
}

tasks.named('publish') {
    finalizedBy tasks.named('ensuringDeploymentVisibility')
}