apply plugin: 'com.android.library'
apply from: '../../gradle/android_extension.gradle'

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 34
    }

    namespace 'com.pitaya.mobile.uinspector.optional.autoinstall'
}

dependencies {
    api project(":Uinspector-api")
}

ext {
    libraryName = 'Uinspector-optional-autoinstall'
    libraryDescription = 'A UI inspector to traverse a view hierarchy on Android'
    siteUrl = 'https://github.com/YvesCheung/UInspector'
    gitUrl = 'https://github.com/YvesCheung/UInspector.git'
    libraryVersion = version
}

apply from: "../../gradle/publish.gradle"